development:
    adapter: sqlite3
    database: db/development_domain_portfolio.db
    pool: 5
    timeout: 5000

test:
    adapter: sqlite3
    database: db/test_domain_portfolio.db
    pool: 5
    timeout: 5000
